openapi: 3.0.0
info:
  title: Employee API
  version: 1.0.0
servers:
  - url: http://mockbintareget.apigee.net
paths:
  /employee:
    get:
      summary: Retrieve employee data
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EmployeeResponse'
components:
  schemas:
    EmployeeResponse:
      type: object
      properties:
        employees:
          type: array
          items:
            $ref: '#/components/schemas/Employee'
    Employee:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        position:
          type: string
