openapi: 3.0.0
info:
  title: XML API
  version: 1.0.0
servers:
  - url: https://httpbin.org
paths:
  /xml:
    get:
      summary: Retrieve XML data
      responses:
        '200':
          description: Successful response
          content:
            application/xml:
              schema:
                $ref: '#/components/schemas/XmlData'
components:
  schemas:
    XmlData:
      type: object
      properties:
        data:
          type: string
